<html>
<head>
  <title>NotIDE</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
  <link rel="stylesheet" href="/ide.css?1">
</head>
<body>
      
      
      
  <ul id="files"><?=tree()?></ul>
  
  <div id="editor_container">
    <div id="editor"></div>
  </div>
  
  <div id="search">
    <input placeholder="Search files...">
    <ul></ul>
  </div>
  
  <div id="error"></div>
  
  
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
          integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
          crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js"
          integrity="sha256-5Xkhn3k/1rbXB+Q/DX/2RuAtaB4dRRyQvMs83prFjpM="
          crossorigin="anonymous"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ext-modelist.js"
          integrity="sha256-Eq83mfVraqpouXYtwjYSEvTt6JM7k1VrhsebwRs06AM="
          crossorigin="anonymous"></script>

  <script><?php include 'ide.js'; ?></script>


  <ul id="latest"></ul>


  <ul id="actions">
	  <?php foreach ( $actions as $action => $cb ) { ?>
	    <li><?=$action?></li>
	  <?php } ?>
  </ul>

    <div id="console" style="display: none;"><pre>...</pre></div>
  </body>
</html>
