<html>
<head>
  <title>notIDE</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
  <link rel="stylesheet" href="/ide.css?4">
</head>
<body>
  
  <div id="search">
    <input placeholder="Search files...">
    <button>↻</button>
  </div>
  
  <ul id="files"></ul>
  <input id="new_file" placeholder="New file..." />
  
  <div id="editor_container">
    <div id="editor"></div>
  </div>
  
  <div id="error"></div>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
          integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
          crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js"
          integrity="sha256-5Xkhn3k/1rbXB+Q/DX/2RuAtaB4dRRyQvMs83prFjpM="
          crossorigin="anonymous"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ext-modelist.js"
          integrity="sha256-Eq83mfVraqpouXYtwjYSEvTt6JM7k1VrhsebwRs06AM="
          crossorigin="anonymous"></script>

  <script>var key = <?=json_encode($key)?>;</script>
  <script><?php include 'ide.js'; ?></script>
  
</body>
</html>
