<html>
<head>
  <title>notIDE - edit local code online</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
  <link rel="stylesheet" href="/ide.css?4">
</head>
<body class="public">
  
  <h1>not<b>IDE</b></h1>
  <div id="public">
    <p class="description">Edit code on your servers or local machines online</p>
    
    <p><b>1</b> Open terminal and go to the dir your code is in:</p>
    <pre><code>cd /path/to/code && python3 <(curl -s https://notide.cc/i)</code></pre>

    <p><b>2</b> Open generated unique link in your browser:</p>
    <pre><code>To edit "/path/to/code" point your browser to:
<strong>notide.cc/qw...0g</strong>

press ctrl+c when finished</code></pre>

  <p><b>3</b> Now edit your files:</p>
  </div>
  
  <img src="/demo.png" class="demo"/>
  
  <p class="foot">
    We're opensource, contribute and give feedbacks on <a href="https://github.com/mrcrypster/notide" target="_blank">our github</a>
  </p>
  
  
  <script>
    document.querySelectorAll('pre code').forEach(function(el) {
      el.addEventListener('click', function() {
        var range = document.createRange();
        range.selectNode(el);
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(range);
        
        navigator.clipboard.writeText(el.innerText);
      });
    });
  </script>
  
</body>
</html>
