<html>
<head>
  <title>notIDE - edit local code online</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
  <link rel="stylesheet" href="/ide.css?5">
</head>
<body class="public">
  
  <h1>not<b>IDE</b></h1>
  <p class="description">edit / local | server / code online</p>
  
  <div id="public">
    <p>Open terminal and launch NotIDE client in folder with your code:</p>
    <pre><code>cd /path/to/code && <b>python3 <(curl -s https://notide.cc/i)</b></code></pre>

    <p>Open generated unique link and edit your files in the browser:</p>
  </div>
  
  <img src="/demo.png" class="demo"/>
  
  <div class="features">
  <ul>
    <li>Autosave while editing
    <li>Syntax highlight using <a href="https://ace.c9.io/">ace editor</a>
    <li>Create new files
    <li><code>double click</code> file name to move/rename
    <li><code>Shift + single click</code> file/dir name to remove
    <li>Search files by name
    <li><a href="https://github.com/mrcrypster/notide/blob/main/notide.py">Python-based client</a> with automatic reconnection
  </ul>
  </div>
  
  <p class="foot">
    Opensource. Contribute/feedbacks on <a href="https://github.com/mrcrypster/notide" target="_blank">github</a>.
    Created by <a href="https://github.com/mrcrypster">mrcrypster</a> in 2022.
  </p>
  
  
  <script>
    document.querySelectorAll('pre code').forEach(function(el) {
      el.addEventListener('click', function() {
        var range = document.createRange();
        range.selectNode(el.querySelector('b'));
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(range);
        
        navigator.clipboard.writeText(el.innerText);
      });
    });
  </script>
  
</body>
</html>
