<html>
<head>
  <title>notIDE - edit local code online</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
  <link rel="stylesheet" href="/ide.css?5">
</head>
<body class="public">
  
  <h1>not<b>IDE</b></h1>
  <p class="description">edit / local | server / code online</p>

  <div class="features">
    <ul>
      <li>Create/rename/move/delete files/folders
      <li>Drag-and-drop files upload
      <li>Syntax highlight using <a href="https://ace.c9.io/">Ace editor</a>
      <li>Autosaving changes
      <li>Search files by name
      <li>Python-based client local client
      <li>Cross-files undo manager
      <li>Cursor position/scroll depth autosave
    </ul>
  </div>
  
  <div id="public">
    <p>Launch NotIDE client in folder with your code:</p>
    <pre><code>cd /path/to/code && <b>python3 <(curl -s https://notide.cc/i)</b></code></pre>
    
    <p>Python client uses websockets for best performance, so don't forget to install it:</p>
    <pre class="small"><code>pip install websockets</code></pre>

    <p>Open generated link:</p>
    <img src="/example-terminal.png" class="demo"/>

    <p>Edit your code:</p>
    <img src="/demo.png" class="demo"/>
  </div>
  
  <p class="foot">
    Opensource. Contribute/feedbacks on <a href="https://github.com/mrcrypster/notide" target="_blank">github</a>.
    Created by <a href="https://github.com/mrcrypster">mrcrypster</a> in 2022.
  </p>
  
  
  <script>
    document.querySelectorAll('pre code').forEach(function(el) {
      el.addEventListener('click', function() {
        var range = document.createRange();
        range.selectNode(el.querySelector('b'));
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(range);
        
        navigator.clipboard.writeText(el.innerText);
      });
    });
  </script>
  
</body>
</html>
